twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/layout.html.twig']
    globals:
        instance_repository: '@App\Repository\InstanceRepository'
