schedule:
  hide_unscheduled: false
  concerts:
    - Συναυλία στα γρασίδια της Φιλοσοφικής
  mark_fresh: true
  show_unscheduled_concerts: false
  draft: true
  debug_indexes: false
xelatex:
  fonts:
    main: Times New Roman
    sans: Arial
    mono: Latin Modern Mono
default_date: ~